export {dracula, draculaTheme, draculaHighlightStyle} from './themes/dracula'
export {solarizedLight, solarizedLightTheme, solarizedLightHighlightStyle} from './themes/solarized-light'
export {solarizedDark, solarizedDarkTheme, solarizedDarkHighlightStyle} from './themes/solarized-dark'
export {materialDark, materialDarkTheme, materialDarkHighlightStyle} from './themes/material-dark'
export {materialLight, materialLightTheme, materialLightHighlightStyle} from './themes/material-light'
export {githubLight, githubLightTheme, githubLightHighlightStyle} from './themes/github-light'
export {githubDark, githubDarkTheme, githubDarkHighlightStyle} from './themes/github-dark'
