export {dracula, draculaTheme, draculaHighlightStyle} from './theme/dracula'
export {solarizedLight, solarizedLightTheme, solarizedLightHighlightStyle} from './theme/solarized-light'
export {solarizedDark, solarizedDarkTheme, solarizedDarkHighlightStyle} from './theme/solarized-dark'
export {materialDark, materialDarkTheme, materialDarkHighlightStyle} from './theme/material-dark'
export {materialLight, materialLightTheme, materialLightHighlightStyle} from './theme/material-light'
export {githubLight, githubLightTheme, githubLightHighlightStyle} from './theme/github-light'
export {githubDark, githubDarkTheme, githubDarkHighlightStyle} from './theme/github-dark'
